name: Main Pipeline

on:
    push:
        branches: [main]

permissions: 
    contents: read

jobs:
    build-test:
        uses: ./.github/workflows/reusable-build-test.yml
        with:
            run_tests: true


    build-docker:
        needs: build-test
        uses: ./.github/workflows/reusable-docker.yml
        secrets:
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    scan-docker-image:
        needs: build-docker
        runs-on: ubuntu-latest
        steps:
            - name: Scan Docker Image for Vulnerabilities
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: "${{vars.DOCKER_USERNAME}}/repo:${{ github.sha }}"
                format: 'table'
                exit-code: '1'
                severity: 'CRITICAL,HIGH'

    deploy:
        needs: [build-docker, scan-docker-image]
        runs-on: ubuntu-latest
        steps:
            - name: Print Deploying image <image_url> to production
              run: 'echo "Deploying image: ${{ needs.build-docker.outputs.image-url }} to production"'
    